backend:
  name: git-gateway
  branch: main

media_folder: images/uploads
public_folder: /images/uploads

collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "about"
        label: "About Me"
        file: "content/about.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
